package org.tyuan.service.data.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OAuth2RegistrationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public OAuth2RegistrationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(String value) {
            addCriterion("client_id =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(String value) {
            addCriterion("client_id <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(String value) {
            addCriterion("client_id >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("client_id >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(String value) {
            addCriterion("client_id <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(String value) {
            addCriterion("client_id <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLike(String value) {
            addCriterion("client_id like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotLike(String value) {
            addCriterion("client_id not like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<String> values) {
            addCriterion("client_id in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<String> values) {
            addCriterion("client_id not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(String value1, String value2) {
            addCriterion("client_id between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(String value1, String value2) {
            addCriterion("client_id not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientSecretIsNull() {
            addCriterion("client_secret is null");
            return (Criteria) this;
        }

        public Criteria andClientSecretIsNotNull() {
            addCriterion("client_secret is not null");
            return (Criteria) this;
        }

        public Criteria andClientSecretEqualTo(String value) {
            addCriterion("client_secret =", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotEqualTo(String value) {
            addCriterion("client_secret <>", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretGreaterThan(String value) {
            addCriterion("client_secret >", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretGreaterThanOrEqualTo(String value) {
            addCriterion("client_secret >=", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretLessThan(String value) {
            addCriterion("client_secret <", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretLessThanOrEqualTo(String value) {
            addCriterion("client_secret <=", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretLike(String value) {
            addCriterion("client_secret like", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotLike(String value) {
            addCriterion("client_secret not like", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretIn(List<String> values) {
            addCriterion("client_secret in", values, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotIn(List<String> values) {
            addCriterion("client_secret not in", values, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretBetween(String value1, String value2) {
            addCriterion("client_secret between", value1, value2, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotBetween(String value1, String value2) {
            addCriterion("client_secret not between", value1, value2, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriIsNull() {
            addCriterion("authorization_uri is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriIsNotNull() {
            addCriterion("authorization_uri is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriEqualTo(String value) {
            addCriterion("authorization_uri =", value, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriNotEqualTo(String value) {
            addCriterion("authorization_uri <>", value, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriGreaterThan(String value) {
            addCriterion("authorization_uri >", value, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriGreaterThanOrEqualTo(String value) {
            addCriterion("authorization_uri >=", value, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriLessThan(String value) {
            addCriterion("authorization_uri <", value, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriLessThanOrEqualTo(String value) {
            addCriterion("authorization_uri <=", value, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriLike(String value) {
            addCriterion("authorization_uri like", value, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriNotLike(String value) {
            addCriterion("authorization_uri not like", value, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriIn(List<String> values) {
            addCriterion("authorization_uri in", values, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriNotIn(List<String> values) {
            addCriterion("authorization_uri not in", values, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriBetween(String value1, String value2) {
            addCriterion("authorization_uri between", value1, value2, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andAuthorizationUriNotBetween(String value1, String value2) {
            addCriterion("authorization_uri not between", value1, value2, "authorizationUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriIsNull() {
            addCriterion("token_uri is null");
            return (Criteria) this;
        }

        public Criteria andTokenUriIsNotNull() {
            addCriterion("token_uri is not null");
            return (Criteria) this;
        }

        public Criteria andTokenUriEqualTo(String value) {
            addCriterion("token_uri =", value, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriNotEqualTo(String value) {
            addCriterion("token_uri <>", value, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriGreaterThan(String value) {
            addCriterion("token_uri >", value, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriGreaterThanOrEqualTo(String value) {
            addCriterion("token_uri >=", value, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriLessThan(String value) {
            addCriterion("token_uri <", value, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriLessThanOrEqualTo(String value) {
            addCriterion("token_uri <=", value, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriLike(String value) {
            addCriterion("token_uri like", value, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriNotLike(String value) {
            addCriterion("token_uri not like", value, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriIn(List<String> values) {
            addCriterion("token_uri in", values, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriNotIn(List<String> values) {
            addCriterion("token_uri not in", values, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriBetween(String value1, String value2) {
            addCriterion("token_uri between", value1, value2, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andTokenUriNotBetween(String value1, String value2) {
            addCriterion("token_uri not between", value1, value2, "tokenUri");
            return (Criteria) this;
        }

        public Criteria andScopeIsNull() {
            addCriterion("scope is null");
            return (Criteria) this;
        }

        public Criteria andScopeIsNotNull() {
            addCriterion("scope is not null");
            return (Criteria) this;
        }

        public Criteria andScopeEqualTo(String value) {
            addCriterion("scope =", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotEqualTo(String value) {
            addCriterion("scope <>", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThan(String value) {
            addCriterion("scope >", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThanOrEqualTo(String value) {
            addCriterion("scope >=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThan(String value) {
            addCriterion("scope <", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThanOrEqualTo(String value) {
            addCriterion("scope <=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLike(String value) {
            addCriterion("scope like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotLike(String value) {
            addCriterion("scope not like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeIn(List<String> values) {
            addCriterion("scope in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotIn(List<String> values) {
            addCriterion("scope not in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeBetween(String value1, String value2) {
            addCriterion("scope between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotBetween(String value1, String value2) {
            addCriterion("scope not between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andPlatformsIsNull() {
            addCriterion("platforms is null");
            return (Criteria) this;
        }

        public Criteria andPlatformsIsNotNull() {
            addCriterion("platforms is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformsEqualTo(String value) {
            addCriterion("platforms =", value, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsNotEqualTo(String value) {
            addCriterion("platforms <>", value, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsGreaterThan(String value) {
            addCriterion("platforms >", value, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsGreaterThanOrEqualTo(String value) {
            addCriterion("platforms >=", value, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsLessThan(String value) {
            addCriterion("platforms <", value, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsLessThanOrEqualTo(String value) {
            addCriterion("platforms <=", value, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsLike(String value) {
            addCriterion("platforms like", value, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsNotLike(String value) {
            addCriterion("platforms not like", value, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsIn(List<String> values) {
            addCriterion("platforms in", values, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsNotIn(List<String> values) {
            addCriterion("platforms not in", values, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsBetween(String value1, String value2) {
            addCriterion("platforms between", value1, value2, "platforms");
            return (Criteria) this;
        }

        public Criteria andPlatformsNotBetween(String value1, String value2) {
            addCriterion("platforms not between", value1, value2, "platforms");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriIsNull() {
            addCriterion("user_info_uri is null");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriIsNotNull() {
            addCriterion("user_info_uri is not null");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriEqualTo(String value) {
            addCriterion("user_info_uri =", value, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriNotEqualTo(String value) {
            addCriterion("user_info_uri <>", value, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriGreaterThan(String value) {
            addCriterion("user_info_uri >", value, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriGreaterThanOrEqualTo(String value) {
            addCriterion("user_info_uri >=", value, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriLessThan(String value) {
            addCriterion("user_info_uri <", value, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriLessThanOrEqualTo(String value) {
            addCriterion("user_info_uri <=", value, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriLike(String value) {
            addCriterion("user_info_uri like", value, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriNotLike(String value) {
            addCriterion("user_info_uri not like", value, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriIn(List<String> values) {
            addCriterion("user_info_uri in", values, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriNotIn(List<String> values) {
            addCriterion("user_info_uri not in", values, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriBetween(String value1, String value2) {
            addCriterion("user_info_uri between", value1, value2, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserInfoUriNotBetween(String value1, String value2) {
            addCriterion("user_info_uri not between", value1, value2, "userInfoUri");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameIsNull() {
            addCriterion("user_name_attribute_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameIsNotNull() {
            addCriterion("user_name_attribute_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameEqualTo(String value) {
            addCriterion("user_name_attribute_name =", value, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameNotEqualTo(String value) {
            addCriterion("user_name_attribute_name <>", value, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameGreaterThan(String value) {
            addCriterion("user_name_attribute_name >", value, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name_attribute_name >=", value, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameLessThan(String value) {
            addCriterion("user_name_attribute_name <", value, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameLessThanOrEqualTo(String value) {
            addCriterion("user_name_attribute_name <=", value, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameLike(String value) {
            addCriterion("user_name_attribute_name like", value, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameNotLike(String value) {
            addCriterion("user_name_attribute_name not like", value, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameIn(List<String> values) {
            addCriterion("user_name_attribute_name in", values, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameNotIn(List<String> values) {
            addCriterion("user_name_attribute_name not in", values, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameBetween(String value1, String value2) {
            addCriterion("user_name_attribute_name between", value1, value2, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andUserNameAttributeNameNotBetween(String value1, String value2) {
            addCriterion("user_name_attribute_name not between", value1, value2, "userNameAttributeName");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriIsNull() {
            addCriterion("jwk_set_uri is null");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriIsNotNull() {
            addCriterion("jwk_set_uri is not null");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriEqualTo(String value) {
            addCriterion("jwk_set_uri =", value, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriNotEqualTo(String value) {
            addCriterion("jwk_set_uri <>", value, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriGreaterThan(String value) {
            addCriterion("jwk_set_uri >", value, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriGreaterThanOrEqualTo(String value) {
            addCriterion("jwk_set_uri >=", value, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriLessThan(String value) {
            addCriterion("jwk_set_uri <", value, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriLessThanOrEqualTo(String value) {
            addCriterion("jwk_set_uri <=", value, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriLike(String value) {
            addCriterion("jwk_set_uri like", value, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriNotLike(String value) {
            addCriterion("jwk_set_uri not like", value, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriIn(List<String> values) {
            addCriterion("jwk_set_uri in", values, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriNotIn(List<String> values) {
            addCriterion("jwk_set_uri not in", values, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriBetween(String value1, String value2) {
            addCriterion("jwk_set_uri between", value1, value2, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andJwkSetUriNotBetween(String value1, String value2) {
            addCriterion("jwk_set_uri not between", value1, value2, "jwkSetUri");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodIsNull() {
            addCriterion("client_authentication_method is null");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodIsNotNull() {
            addCriterion("client_authentication_method is not null");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodEqualTo(String value) {
            addCriterion("client_authentication_method =", value, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodNotEqualTo(String value) {
            addCriterion("client_authentication_method <>", value, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodGreaterThan(String value) {
            addCriterion("client_authentication_method >", value, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodGreaterThanOrEqualTo(String value) {
            addCriterion("client_authentication_method >=", value, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodLessThan(String value) {
            addCriterion("client_authentication_method <", value, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodLessThanOrEqualTo(String value) {
            addCriterion("client_authentication_method <=", value, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodLike(String value) {
            addCriterion("client_authentication_method like", value, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodNotLike(String value) {
            addCriterion("client_authentication_method not like", value, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodIn(List<String> values) {
            addCriterion("client_authentication_method in", values, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodNotIn(List<String> values) {
            addCriterion("client_authentication_method not in", values, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodBetween(String value1, String value2) {
            addCriterion("client_authentication_method between", value1, value2, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodNotBetween(String value1, String value2) {
            addCriterion("client_authentication_method not between", value1, value2, "clientAuthenticationMethod");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelIsNull() {
            addCriterion("login_button_label is null");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelIsNotNull() {
            addCriterion("login_button_label is not null");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelEqualTo(String value) {
            addCriterion("login_button_label =", value, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelNotEqualTo(String value) {
            addCriterion("login_button_label <>", value, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelGreaterThan(String value) {
            addCriterion("login_button_label >", value, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelGreaterThanOrEqualTo(String value) {
            addCriterion("login_button_label >=", value, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelLessThan(String value) {
            addCriterion("login_button_label <", value, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelLessThanOrEqualTo(String value) {
            addCriterion("login_button_label <=", value, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelLike(String value) {
            addCriterion("login_button_label like", value, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelNotLike(String value) {
            addCriterion("login_button_label not like", value, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelIn(List<String> values) {
            addCriterion("login_button_label in", values, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelNotIn(List<String> values) {
            addCriterion("login_button_label not in", values, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelBetween(String value1, String value2) {
            addCriterion("login_button_label between", value1, value2, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonLabelNotBetween(String value1, String value2) {
            addCriterion("login_button_label not between", value1, value2, "loginButtonLabel");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconIsNull() {
            addCriterion("login_button_icon is null");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconIsNotNull() {
            addCriterion("login_button_icon is not null");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconEqualTo(String value) {
            addCriterion("login_button_icon =", value, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconNotEqualTo(String value) {
            addCriterion("login_button_icon <>", value, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconGreaterThan(String value) {
            addCriterion("login_button_icon >", value, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconGreaterThanOrEqualTo(String value) {
            addCriterion("login_button_icon >=", value, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconLessThan(String value) {
            addCriterion("login_button_icon <", value, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconLessThanOrEqualTo(String value) {
            addCriterion("login_button_icon <=", value, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconLike(String value) {
            addCriterion("login_button_icon like", value, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconNotLike(String value) {
            addCriterion("login_button_icon not like", value, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconIn(List<String> values) {
            addCriterion("login_button_icon in", values, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconNotIn(List<String> values) {
            addCriterion("login_button_icon not in", values, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconBetween(String value1, String value2) {
            addCriterion("login_button_icon between", value1, value2, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andLoginButtonIconNotBetween(String value1, String value2) {
            addCriterion("login_button_icon not between", value1, value2, "loginButtonIcon");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationIsNull() {
            addCriterion("allow_user_creation is null");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationIsNotNull() {
            addCriterion("allow_user_creation is not null");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationEqualTo(Boolean value) {
            addCriterion("allow_user_creation =", value, "allowUserCreation");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationNotEqualTo(Boolean value) {
            addCriterion("allow_user_creation <>", value, "allowUserCreation");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationGreaterThan(Boolean value) {
            addCriterion("allow_user_creation >", value, "allowUserCreation");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationGreaterThanOrEqualTo(Boolean value) {
            addCriterion("allow_user_creation >=", value, "allowUserCreation");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationLessThan(Boolean value) {
            addCriterion("allow_user_creation <", value, "allowUserCreation");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationLessThanOrEqualTo(Boolean value) {
            addCriterion("allow_user_creation <=", value, "allowUserCreation");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationIn(List<Boolean> values) {
            addCriterion("allow_user_creation in", values, "allowUserCreation");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationNotIn(List<Boolean> values) {
            addCriterion("allow_user_creation not in", values, "allowUserCreation");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationBetween(Boolean value1, Boolean value2) {
            addCriterion("allow_user_creation between", value1, value2, "allowUserCreation");
            return (Criteria) this;
        }

        public Criteria andAllowUserCreationNotBetween(Boolean value1, Boolean value2) {
            addCriterion("allow_user_creation not between", value1, value2, "allowUserCreation");
            return (Criteria) this;
        }

        public Criteria andActivateUserIsNull() {
            addCriterion("activate_user is null");
            return (Criteria) this;
        }

        public Criteria andActivateUserIsNotNull() {
            addCriterion("activate_user is not null");
            return (Criteria) this;
        }

        public Criteria andActivateUserEqualTo(Boolean value) {
            addCriterion("activate_user =", value, "activateUser");
            return (Criteria) this;
        }

        public Criteria andActivateUserNotEqualTo(Boolean value) {
            addCriterion("activate_user <>", value, "activateUser");
            return (Criteria) this;
        }

        public Criteria andActivateUserGreaterThan(Boolean value) {
            addCriterion("activate_user >", value, "activateUser");
            return (Criteria) this;
        }

        public Criteria andActivateUserGreaterThanOrEqualTo(Boolean value) {
            addCriterion("activate_user >=", value, "activateUser");
            return (Criteria) this;
        }

        public Criteria andActivateUserLessThan(Boolean value) {
            addCriterion("activate_user <", value, "activateUser");
            return (Criteria) this;
        }

        public Criteria andActivateUserLessThanOrEqualTo(Boolean value) {
            addCriterion("activate_user <=", value, "activateUser");
            return (Criteria) this;
        }

        public Criteria andActivateUserIn(List<Boolean> values) {
            addCriterion("activate_user in", values, "activateUser");
            return (Criteria) this;
        }

        public Criteria andActivateUserNotIn(List<Boolean> values) {
            addCriterion("activate_user not in", values, "activateUser");
            return (Criteria) this;
        }

        public Criteria andActivateUserBetween(Boolean value1, Boolean value2) {
            addCriterion("activate_user between", value1, value2, "activateUser");
            return (Criteria) this;
        }

        public Criteria andActivateUserNotBetween(Boolean value1, Boolean value2) {
            addCriterion("activate_user not between", value1, value2, "activateUser");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyIsNull() {
            addCriterion("basic_email_attribute_key is null");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyIsNotNull() {
            addCriterion("basic_email_attribute_key is not null");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyEqualTo(String value) {
            addCriterion("basic_email_attribute_key =", value, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyNotEqualTo(String value) {
            addCriterion("basic_email_attribute_key <>", value, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyGreaterThan(String value) {
            addCriterion("basic_email_attribute_key >", value, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyGreaterThanOrEqualTo(String value) {
            addCriterion("basic_email_attribute_key >=", value, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyLessThan(String value) {
            addCriterion("basic_email_attribute_key <", value, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyLessThanOrEqualTo(String value) {
            addCriterion("basic_email_attribute_key <=", value, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyLike(String value) {
            addCriterion("basic_email_attribute_key like", value, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyNotLike(String value) {
            addCriterion("basic_email_attribute_key not like", value, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyIn(List<String> values) {
            addCriterion("basic_email_attribute_key in", values, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyNotIn(List<String> values) {
            addCriterion("basic_email_attribute_key not in", values, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyBetween(String value1, String value2) {
            addCriterion("basic_email_attribute_key between", value1, value2, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicEmailAttributeKeyNotBetween(String value1, String value2) {
            addCriterion("basic_email_attribute_key not between", value1, value2, "basicEmailAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyIsNull() {
            addCriterion("basic_first_name_attribute_key is null");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyIsNotNull() {
            addCriterion("basic_first_name_attribute_key is not null");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyEqualTo(String value) {
            addCriterion("basic_first_name_attribute_key =", value, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyNotEqualTo(String value) {
            addCriterion("basic_first_name_attribute_key <>", value, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyGreaterThan(String value) {
            addCriterion("basic_first_name_attribute_key >", value, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyGreaterThanOrEqualTo(String value) {
            addCriterion("basic_first_name_attribute_key >=", value, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyLessThan(String value) {
            addCriterion("basic_first_name_attribute_key <", value, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyLessThanOrEqualTo(String value) {
            addCriterion("basic_first_name_attribute_key <=", value, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyLike(String value) {
            addCriterion("basic_first_name_attribute_key like", value, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyNotLike(String value) {
            addCriterion("basic_first_name_attribute_key not like", value, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyIn(List<String> values) {
            addCriterion("basic_first_name_attribute_key in", values, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyNotIn(List<String> values) {
            addCriterion("basic_first_name_attribute_key not in", values, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyBetween(String value1, String value2) {
            addCriterion("basic_first_name_attribute_key between", value1, value2, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicFirstNameAttributeKeyNotBetween(String value1, String value2) {
            addCriterion("basic_first_name_attribute_key not between", value1, value2, "basicFirstNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyIsNull() {
            addCriterion("basic_last_name_attribute_key is null");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyIsNotNull() {
            addCriterion("basic_last_name_attribute_key is not null");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyEqualTo(String value) {
            addCriterion("basic_last_name_attribute_key =", value, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyNotEqualTo(String value) {
            addCriterion("basic_last_name_attribute_key <>", value, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyGreaterThan(String value) {
            addCriterion("basic_last_name_attribute_key >", value, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyGreaterThanOrEqualTo(String value) {
            addCriterion("basic_last_name_attribute_key >=", value, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyLessThan(String value) {
            addCriterion("basic_last_name_attribute_key <", value, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyLessThanOrEqualTo(String value) {
            addCriterion("basic_last_name_attribute_key <=", value, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyLike(String value) {
            addCriterion("basic_last_name_attribute_key like", value, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyNotLike(String value) {
            addCriterion("basic_last_name_attribute_key not like", value, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyIn(List<String> values) {
            addCriterion("basic_last_name_attribute_key in", values, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyNotIn(List<String> values) {
            addCriterion("basic_last_name_attribute_key not in", values, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyBetween(String value1, String value2) {
            addCriterion("basic_last_name_attribute_key between", value1, value2, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicLastNameAttributeKeyNotBetween(String value1, String value2) {
            addCriterion("basic_last_name_attribute_key not between", value1, value2, "basicLastNameAttributeKey");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyIsNull() {
            addCriterion("basic_tenant_name_strategy is null");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyIsNotNull() {
            addCriterion("basic_tenant_name_strategy is not null");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyEqualTo(String value) {
            addCriterion("basic_tenant_name_strategy =", value, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyNotEqualTo(String value) {
            addCriterion("basic_tenant_name_strategy <>", value, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyGreaterThan(String value) {
            addCriterion("basic_tenant_name_strategy >", value, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyGreaterThanOrEqualTo(String value) {
            addCriterion("basic_tenant_name_strategy >=", value, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyLessThan(String value) {
            addCriterion("basic_tenant_name_strategy <", value, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyLessThanOrEqualTo(String value) {
            addCriterion("basic_tenant_name_strategy <=", value, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyLike(String value) {
            addCriterion("basic_tenant_name_strategy like", value, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyNotLike(String value) {
            addCriterion("basic_tenant_name_strategy not like", value, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyIn(List<String> values) {
            addCriterion("basic_tenant_name_strategy in", values, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyNotIn(List<String> values) {
            addCriterion("basic_tenant_name_strategy not in", values, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyBetween(String value1, String value2) {
            addCriterion("basic_tenant_name_strategy between", value1, value2, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNameStrategyNotBetween(String value1, String value2) {
            addCriterion("basic_tenant_name_strategy not between", value1, value2, "basicTenantNameStrategy");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternIsNull() {
            addCriterion("basic_tenant_name_pattern is null");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternIsNotNull() {
            addCriterion("basic_tenant_name_pattern is not null");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternEqualTo(String value) {
            addCriterion("basic_tenant_name_pattern =", value, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternNotEqualTo(String value) {
            addCriterion("basic_tenant_name_pattern <>", value, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternGreaterThan(String value) {
            addCriterion("basic_tenant_name_pattern >", value, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternGreaterThanOrEqualTo(String value) {
            addCriterion("basic_tenant_name_pattern >=", value, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternLessThan(String value) {
            addCriterion("basic_tenant_name_pattern <", value, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternLessThanOrEqualTo(String value) {
            addCriterion("basic_tenant_name_pattern <=", value, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternLike(String value) {
            addCriterion("basic_tenant_name_pattern like", value, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternNotLike(String value) {
            addCriterion("basic_tenant_name_pattern not like", value, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternIn(List<String> values) {
            addCriterion("basic_tenant_name_pattern in", values, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternNotIn(List<String> values) {
            addCriterion("basic_tenant_name_pattern not in", values, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternBetween(String value1, String value2) {
            addCriterion("basic_tenant_name_pattern between", value1, value2, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicTenantNamePatternNotBetween(String value1, String value2) {
            addCriterion("basic_tenant_name_pattern not between", value1, value2, "basicTenantNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternIsNull() {
            addCriterion("basic_customer_name_pattern is null");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternIsNotNull() {
            addCriterion("basic_customer_name_pattern is not null");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternEqualTo(String value) {
            addCriterion("basic_customer_name_pattern =", value, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternNotEqualTo(String value) {
            addCriterion("basic_customer_name_pattern <>", value, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternGreaterThan(String value) {
            addCriterion("basic_customer_name_pattern >", value, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternGreaterThanOrEqualTo(String value) {
            addCriterion("basic_customer_name_pattern >=", value, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternLessThan(String value) {
            addCriterion("basic_customer_name_pattern <", value, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternLessThanOrEqualTo(String value) {
            addCriterion("basic_customer_name_pattern <=", value, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternLike(String value) {
            addCriterion("basic_customer_name_pattern like", value, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternNotLike(String value) {
            addCriterion("basic_customer_name_pattern not like", value, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternIn(List<String> values) {
            addCriterion("basic_customer_name_pattern in", values, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternNotIn(List<String> values) {
            addCriterion("basic_customer_name_pattern not in", values, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternBetween(String value1, String value2) {
            addCriterion("basic_customer_name_pattern between", value1, value2, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicCustomerNamePatternNotBetween(String value1, String value2) {
            addCriterion("basic_customer_name_pattern not between", value1, value2, "basicCustomerNamePattern");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameIsNull() {
            addCriterion("basic_default_dashboard_name is null");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameIsNotNull() {
            addCriterion("basic_default_dashboard_name is not null");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameEqualTo(String value) {
            addCriterion("basic_default_dashboard_name =", value, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameNotEqualTo(String value) {
            addCriterion("basic_default_dashboard_name <>", value, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameGreaterThan(String value) {
            addCriterion("basic_default_dashboard_name >", value, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameGreaterThanOrEqualTo(String value) {
            addCriterion("basic_default_dashboard_name >=", value, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameLessThan(String value) {
            addCriterion("basic_default_dashboard_name <", value, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameLessThanOrEqualTo(String value) {
            addCriterion("basic_default_dashboard_name <=", value, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameLike(String value) {
            addCriterion("basic_default_dashboard_name like", value, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameNotLike(String value) {
            addCriterion("basic_default_dashboard_name not like", value, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameIn(List<String> values) {
            addCriterion("basic_default_dashboard_name in", values, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameNotIn(List<String> values) {
            addCriterion("basic_default_dashboard_name not in", values, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameBetween(String value1, String value2) {
            addCriterion("basic_default_dashboard_name between", value1, value2, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicDefaultDashboardNameNotBetween(String value1, String value2) {
            addCriterion("basic_default_dashboard_name not between", value1, value2, "basicDefaultDashboardName");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenIsNull() {
            addCriterion("basic_always_full_screen is null");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenIsNotNull() {
            addCriterion("basic_always_full_screen is not null");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenEqualTo(Boolean value) {
            addCriterion("basic_always_full_screen =", value, "basicAlwaysFullScreen");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenNotEqualTo(Boolean value) {
            addCriterion("basic_always_full_screen <>", value, "basicAlwaysFullScreen");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenGreaterThan(Boolean value) {
            addCriterion("basic_always_full_screen >", value, "basicAlwaysFullScreen");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenGreaterThanOrEqualTo(Boolean value) {
            addCriterion("basic_always_full_screen >=", value, "basicAlwaysFullScreen");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenLessThan(Boolean value) {
            addCriterion("basic_always_full_screen <", value, "basicAlwaysFullScreen");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenLessThanOrEqualTo(Boolean value) {
            addCriterion("basic_always_full_screen <=", value, "basicAlwaysFullScreen");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenIn(List<Boolean> values) {
            addCriterion("basic_always_full_screen in", values, "basicAlwaysFullScreen");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenNotIn(List<Boolean> values) {
            addCriterion("basic_always_full_screen not in", values, "basicAlwaysFullScreen");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenBetween(Boolean value1, Boolean value2) {
            addCriterion("basic_always_full_screen between", value1, value2, "basicAlwaysFullScreen");
            return (Criteria) this;
        }

        public Criteria andBasicAlwaysFullScreenNotBetween(Boolean value1, Boolean value2) {
            addCriterion("basic_always_full_screen not between", value1, value2, "basicAlwaysFullScreen");
            return (Criteria) this;
        }

        public Criteria andCustomUrlIsNull() {
            addCriterion("custom_url is null");
            return (Criteria) this;
        }

        public Criteria andCustomUrlIsNotNull() {
            addCriterion("custom_url is not null");
            return (Criteria) this;
        }

        public Criteria andCustomUrlEqualTo(String value) {
            addCriterion("custom_url =", value, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlNotEqualTo(String value) {
            addCriterion("custom_url <>", value, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlGreaterThan(String value) {
            addCriterion("custom_url >", value, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlGreaterThanOrEqualTo(String value) {
            addCriterion("custom_url >=", value, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlLessThan(String value) {
            addCriterion("custom_url <", value, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlLessThanOrEqualTo(String value) {
            addCriterion("custom_url <=", value, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlLike(String value) {
            addCriterion("custom_url like", value, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlNotLike(String value) {
            addCriterion("custom_url not like", value, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlIn(List<String> values) {
            addCriterion("custom_url in", values, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlNotIn(List<String> values) {
            addCriterion("custom_url not in", values, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlBetween(String value1, String value2) {
            addCriterion("custom_url between", value1, value2, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUrlNotBetween(String value1, String value2) {
            addCriterion("custom_url not between", value1, value2, "customUrl");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameIsNull() {
            addCriterion("custom_username is null");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameIsNotNull() {
            addCriterion("custom_username is not null");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameEqualTo(String value) {
            addCriterion("custom_username =", value, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameNotEqualTo(String value) {
            addCriterion("custom_username <>", value, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameGreaterThan(String value) {
            addCriterion("custom_username >", value, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("custom_username >=", value, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameLessThan(String value) {
            addCriterion("custom_username <", value, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameLessThanOrEqualTo(String value) {
            addCriterion("custom_username <=", value, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameLike(String value) {
            addCriterion("custom_username like", value, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameNotLike(String value) {
            addCriterion("custom_username not like", value, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameIn(List<String> values) {
            addCriterion("custom_username in", values, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameNotIn(List<String> values) {
            addCriterion("custom_username not in", values, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameBetween(String value1, String value2) {
            addCriterion("custom_username between", value1, value2, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomUsernameNotBetween(String value1, String value2) {
            addCriterion("custom_username not between", value1, value2, "customUsername");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordIsNull() {
            addCriterion("custom_password is null");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordIsNotNull() {
            addCriterion("custom_password is not null");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordEqualTo(String value) {
            addCriterion("custom_password =", value, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordNotEqualTo(String value) {
            addCriterion("custom_password <>", value, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordGreaterThan(String value) {
            addCriterion("custom_password >", value, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("custom_password >=", value, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordLessThan(String value) {
            addCriterion("custom_password <", value, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordLessThanOrEqualTo(String value) {
            addCriterion("custom_password <=", value, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordLike(String value) {
            addCriterion("custom_password like", value, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordNotLike(String value) {
            addCriterion("custom_password not like", value, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordIn(List<String> values) {
            addCriterion("custom_password in", values, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordNotIn(List<String> values) {
            addCriterion("custom_password not in", values, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordBetween(String value1, String value2) {
            addCriterion("custom_password between", value1, value2, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomPasswordNotBetween(String value1, String value2) {
            addCriterion("custom_password not between", value1, value2, "customPassword");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenIsNull() {
            addCriterion("custom_send_token is null");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenIsNotNull() {
            addCriterion("custom_send_token is not null");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenEqualTo(Boolean value) {
            addCriterion("custom_send_token =", value, "customSendToken");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenNotEqualTo(Boolean value) {
            addCriterion("custom_send_token <>", value, "customSendToken");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenGreaterThan(Boolean value) {
            addCriterion("custom_send_token >", value, "customSendToken");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenGreaterThanOrEqualTo(Boolean value) {
            addCriterion("custom_send_token >=", value, "customSendToken");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenLessThan(Boolean value) {
            addCriterion("custom_send_token <", value, "customSendToken");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenLessThanOrEqualTo(Boolean value) {
            addCriterion("custom_send_token <=", value, "customSendToken");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenIn(List<Boolean> values) {
            addCriterion("custom_send_token in", values, "customSendToken");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenNotIn(List<Boolean> values) {
            addCriterion("custom_send_token not in", values, "customSendToken");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenBetween(Boolean value1, Boolean value2) {
            addCriterion("custom_send_token between", value1, value2, "customSendToken");
            return (Criteria) this;
        }

        public Criteria andCustomSendTokenNotBetween(Boolean value1, Boolean value2) {
            addCriterion("custom_send_token not between", value1, value2, "customSendToken");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_registration
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_registration
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}