package com.tyuan.dao.base.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.tyuan.model.base.pojo.OrganizationInstitution;
import com.tyuan.model.base.pojo.OrganizationInstitutionExample.Criteria;
import com.tyuan.model.base.pojo.OrganizationInstitutionExample.Criterion;
import com.tyuan.model.base.pojo.OrganizationInstitutionExample;
import java.util.List;
import java.util.Map;

public class OrganizationInstitutionSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization_institution
     *
     * @mbggenerated
     */
    public String countByExample(OrganizationInstitutionExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("organization_institution");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization_institution
     *
     * @mbggenerated
     */
    public String deleteByExample(OrganizationInstitutionExample example) {
        BEGIN();
        DELETE_FROM("organization_institution");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization_institution
     *
     * @mbggenerated
     */
    public String insertSelective(OrganizationInstitution record) {
        BEGIN();
        INSERT_INTO("organization_institution");
        
        if (record.getParentId() != null) {
            VALUES("parent_id", "#{parentId,jdbcType=BIGINT}");
        }
        
        if (record.getInstCode() != null) {
            VALUES("inst_code", "#{instCode,jdbcType=VARCHAR}");
        }
        
        if (record.getInstName() != null) {
            VALUES("inst_name", "#{instName,jdbcType=VARCHAR}");
        }
        
        if (record.getInstType() != null) {
            VALUES("inst_type", "#{instType,jdbcType=INTEGER}");
        }
        
        if (record.getOwnerUserId() != null) {
            VALUES("owner_user_id", "#{ownerUserId,jdbcType=BIGINT}");
        }
        
        if (record.getInstSort() != null) {
            VALUES("inst_sort", "#{instSort,jdbcType=INTEGER}");
        }
        
        if (record.getInstStatus() != null) {
            VALUES("inst_status", "#{instStatus,jdbcType=INTEGER}");
        }
        
        if (record.getInstDesc() != null) {
            VALUES("inst_desc", "#{instDesc,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            VALUES("create_date", "#{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateDate() != null) {
            VALUES("update_date", "#{updateDate,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization_institution
     *
     * @mbggenerated
     */
    public String selectByExample(OrganizationInstitutionExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("parent_id");
        SELECT("inst_code");
        SELECT("inst_name");
        SELECT("inst_type");
        SELECT("owner_user_id");
        SELECT("inst_sort");
        SELECT("inst_status");
        SELECT("inst_desc");
        SELECT("create_date");
        SELECT("update_date");
        FROM("organization_institution");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization_institution
     *
     * @mbggenerated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        OrganizationInstitution record = (OrganizationInstitution) parameter.get("record");
        OrganizationInstitutionExample example = (OrganizationInstitutionExample) parameter.get("example");
        
        BEGIN();
        UPDATE("organization_institution");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getParentId() != null) {
            SET("parent_id = #{record.parentId,jdbcType=BIGINT}");
        }
        
        if (record.getInstCode() != null) {
            SET("inst_code = #{record.instCode,jdbcType=VARCHAR}");
        }
        
        if (record.getInstName() != null) {
            SET("inst_name = #{record.instName,jdbcType=VARCHAR}");
        }
        
        if (record.getInstType() != null) {
            SET("inst_type = #{record.instType,jdbcType=INTEGER}");
        }
        
        if (record.getOwnerUserId() != null) {
            SET("owner_user_id = #{record.ownerUserId,jdbcType=BIGINT}");
        }
        
        if (record.getInstSort() != null) {
            SET("inst_sort = #{record.instSort,jdbcType=INTEGER}");
        }
        
        if (record.getInstStatus() != null) {
            SET("inst_status = #{record.instStatus,jdbcType=INTEGER}");
        }
        
        if (record.getInstDesc() != null) {
            SET("inst_desc = #{record.instDesc,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateDate() != null) {
            SET("update_date = #{record.updateDate,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization_institution
     *
     * @mbggenerated
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("organization_institution");
        
        SET("id = #{record.id,jdbcType=BIGINT}");
        SET("parent_id = #{record.parentId,jdbcType=BIGINT}");
        SET("inst_code = #{record.instCode,jdbcType=VARCHAR}");
        SET("inst_name = #{record.instName,jdbcType=VARCHAR}");
        SET("inst_type = #{record.instType,jdbcType=INTEGER}");
        SET("owner_user_id = #{record.ownerUserId,jdbcType=BIGINT}");
        SET("inst_sort = #{record.instSort,jdbcType=INTEGER}");
        SET("inst_status = #{record.instStatus,jdbcType=INTEGER}");
        SET("inst_desc = #{record.instDesc,jdbcType=VARCHAR}");
        SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
        SET("update_date = #{record.updateDate,jdbcType=TIMESTAMP}");
        
        OrganizationInstitutionExample example = (OrganizationInstitutionExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization_institution
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(OrganizationInstitution record) {
        BEGIN();
        UPDATE("organization_institution");
        
        if (record.getParentId() != null) {
            SET("parent_id = #{parentId,jdbcType=BIGINT}");
        }
        
        if (record.getInstCode() != null) {
            SET("inst_code = #{instCode,jdbcType=VARCHAR}");
        }
        
        if (record.getInstName() != null) {
            SET("inst_name = #{instName,jdbcType=VARCHAR}");
        }
        
        if (record.getInstType() != null) {
            SET("inst_type = #{instType,jdbcType=INTEGER}");
        }
        
        if (record.getOwnerUserId() != null) {
            SET("owner_user_id = #{ownerUserId,jdbcType=BIGINT}");
        }
        
        if (record.getInstSort() != null) {
            SET("inst_sort = #{instSort,jdbcType=INTEGER}");
        }
        
        if (record.getInstStatus() != null) {
            SET("inst_status = #{instStatus,jdbcType=INTEGER}");
        }
        
        if (record.getInstDesc() != null) {
            SET("inst_desc = #{instDesc,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            SET("create_date = #{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateDate() != null) {
            SET("update_date = #{updateDate,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization_institution
     *
     * @mbggenerated
     */
    protected void applyWhere(OrganizationInstitutionExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}