package org.tyuan.service.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.tyuan.service.data.model.OAuth2Mobile;
import org.tyuan.service.data.model.OAuth2MobileExample;

public interface OAuth2MobileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @SelectProvider(type=OAuth2MobileSqlProvider.class, method="countByExample")
    long countByExample(OAuth2MobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @DeleteProvider(type=OAuth2MobileSqlProvider.class, method="deleteByExample")
    int deleteByExample(OAuth2MobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @Delete({
        "delete from oauth2_mobile",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @Insert({
        "insert into oauth2_mobile (id, create_time, ",
        "update_time, oauth2_params_id, ",
        "pkg_name, app_secret)",
        "values (#{id,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{oauth2ParamsId,jdbcType=VARCHAR}, ",
        "#{pkgName,jdbcType=VARCHAR}, #{appSecret,jdbcType=VARCHAR})"
    })
    int insert(OAuth2Mobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @InsertProvider(type=OAuth2MobileSqlProvider.class, method="insertSelective")
    int insertSelective(OAuth2Mobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @SelectProvider(type=OAuth2MobileSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="oauth2_params_id", property="oauth2ParamsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="pkg_name", property="pkgName", jdbcType=JdbcType.VARCHAR),
        @Result(column="app_secret", property="appSecret", jdbcType=JdbcType.VARCHAR)
    })
    List<OAuth2Mobile> selectByExample(OAuth2MobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, create_time, update_time, oauth2_params_id, pkg_name, app_secret",
        "from oauth2_mobile",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="oauth2_params_id", property="oauth2ParamsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="pkg_name", property="pkgName", jdbcType=JdbcType.VARCHAR),
        @Result(column="app_secret", property="appSecret", jdbcType=JdbcType.VARCHAR)
    })
    OAuth2Mobile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @UpdateProvider(type=OAuth2MobileSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OAuth2Mobile record, @Param("example") OAuth2MobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @UpdateProvider(type=OAuth2MobileSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OAuth2Mobile record, @Param("example") OAuth2MobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @UpdateProvider(type=OAuth2MobileSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OAuth2Mobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_mobile
     *
     * @mbg.generated
     */
    @Update({
        "update oauth2_mobile",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "oauth2_params_id = #{oauth2ParamsId,jdbcType=VARCHAR},",
          "pkg_name = #{pkgName,jdbcType=VARCHAR},",
          "app_secret = #{appSecret,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(OAuth2Mobile record);
}