package org.tyuan.service.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.tyuan.service.data.model.SysMdict;
import org.tyuan.service.data.model.SysMdictExample;

public interface SysMdictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @SelectProvider(type=SysMdictSqlProvider.class, method="countByExample")
    long countByExample(SysMdictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SysMdictSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysMdictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sys_mdict",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sys_mdict (id, create_time, ",
        "update_time, parent_id, ",
        "mdict_name, mdict_sort, ",
        "create_by, update_by, ",
        "remarks, del_flag)",
        "values (#{id,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{parentId,jdbcType=VARCHAR}, ",
        "#{mdictName,jdbcType=VARCHAR}, #{mdictSort,jdbcType=DECIMAL}, ",
        "#{createBy,jdbcType=VARCHAR}, #{updateBy,jdbcType=VARCHAR}, ",
        "#{remarks,jdbcType=VARCHAR}, #{delFlag,jdbcType=BIT})"
    })
    int insert(SysMdict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @InsertProvider(type=SysMdictSqlProvider.class, method="insertSelective")
    int insertSelective(SysMdict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @SelectProvider(type=SysMdictSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="mdict_name", property="mdictName", jdbcType=JdbcType.VARCHAR),
        @Result(column="mdict_sort", property="mdictSort", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_by", property="createBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_by", property="updateBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR),
        @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.BIT)
    })
    List<SysMdict> selectByExample(SysMdictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, create_time, update_time, parent_id, mdict_name, mdict_sort, create_by, ",
        "update_by, remarks, del_flag",
        "from sys_mdict",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="mdict_name", property="mdictName", jdbcType=JdbcType.VARCHAR),
        @Result(column="mdict_sort", property="mdictSort", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_by", property="createBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_by", property="updateBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR),
        @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.BIT)
    })
    SysMdict selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SysMdictSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysMdict record, @Param("example") SysMdictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SysMdictSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysMdict record, @Param("example") SysMdictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SysMdictSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysMdict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mdict
     *
     * @mbg.generated
     */
    @Update({
        "update sys_mdict",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "parent_id = #{parentId,jdbcType=VARCHAR},",
          "mdict_name = #{mdictName,jdbcType=VARCHAR},",
          "mdict_sort = #{mdictSort,jdbcType=DECIMAL},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "update_by = #{updateBy,jdbcType=VARCHAR},",
          "remarks = #{remarks,jdbcType=VARCHAR},",
          "del_flag = #{delFlag,jdbcType=BIT}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysMdict record);
}