package com.tyuan.model.base.vo.sys;

import com.tyuan.model.base.pojo.SysUser;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

import javax.validation.constraints.Pattern;
import java.io.Serializable;

/**
 * @Author: dev@tyuan.design
 * @DateTime: 2020/7/1 9:59
 */
@Getter
@Setter
public class SysUserVo extends SysUser implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.account
     *
     * @mbggenerated
     */
    @NotEmpty(message = "账号不允许为空")
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.name
     *
     * @mbggenerated
     */
    @NotEmpty(message = "用户名称不允许为空")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbggenerated
     */
    @Email(message = "邮箱地址错误")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.mobile
     *
     * @mbggenerated
     */
    @Pattern(regexp = "^1(3|4|5|7|8)\\d{9}$", message = "移动号码格式错误")
    private String mobile;

}
