package com.tyuan.dao.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.tyuan.model.pojo.SysLogExample.Criteria;
import com.tyuan.model.pojo.SysLogExample.Criterion;
import com.tyuan.model.pojo.SysLogExample;
import com.tyuan.model.pojo.SysLogWithBLOBs;
import java.util.List;
import java.util.Map;

public class SysLogSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    public String countByExample(SysLogExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("sys_log");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    public String deleteByExample(SysLogExample example) {
        BEGIN();
        DELETE_FROM("sys_log");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    public String insertSelective(SysLogWithBLOBs record) {
        BEGIN();
        INSERT_INTO("sys_log");

        if (record.getCreateDate() != null) {
            VALUES("create_date", "#{createDate,jdbcType=TIMESTAMP}");
        }

        if (record.getType() != null) {
            VALUES("type", "#{type,jdbcType=BIT}");
        }

        if (record.getTitle() != null) {
            VALUES("title", "#{title,jdbcType=VARCHAR}");
        }

        if (record.getCreateBy() != null) {
            VALUES("create_by", "#{createBy,jdbcType=VARCHAR}");
        }

        if (record.getRemoteAddr() != null) {
            VALUES("remote_addr", "#{remoteAddr,jdbcType=VARCHAR}");
        }

        if (record.getUserAgent() != null) {
            VALUES("user_agent", "#{userAgent,jdbcType=VARCHAR}");
        }

        if (record.getRequestUri() != null) {
            VALUES("request_uri", "#{requestUri,jdbcType=VARCHAR}");
        }

        if (record.getMethod() != null) {
            VALUES("method", "#{method,jdbcType=VARCHAR}");
        }

        if (record.getParams() != null) {
            VALUES("params", "#{params,jdbcType=LONGVARCHAR}");
        }

        if (record.getException() != null) {
            VALUES("exception", "#{exception,jdbcType=LONGVARCHAR}");
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    public String selectByExampleWithBLOBs(SysLogExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("create_date");
        SELECT("type");
        SELECT("title");
        SELECT("create_by");
        SELECT("remote_addr");
        SELECT("user_agent");
        SELECT("request_uri");
        SELECT("method");
        SELECT("params");
        SELECT("exception");
        FROM("sys_log");
        applyWhere(example, false);

        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    public String selectByExample(SysLogExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("create_date");
        SELECT("type");
        SELECT("title");
        SELECT("create_by");
        SELECT("remote_addr");
        SELECT("user_agent");
        SELECT("request_uri");
        SELECT("method");
        FROM("sys_log");
        applyWhere(example, false);

        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        SysLogWithBLOBs record = (SysLogWithBLOBs) parameter.get("record");
        SysLogExample example = (SysLogExample) parameter.get("example");

        BEGIN();
        UPDATE("sys_log");

        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=BIGINT}");
        }

        if (record.getCreateDate() != null) {
            SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
        }

        if (record.getType() != null) {
            SET("type = #{record.type,jdbcType=BIT}");
        }

        if (record.getTitle() != null) {
            SET("title = #{record.title,jdbcType=VARCHAR}");
        }

        if (record.getCreateBy() != null) {
            SET("create_by = #{record.createBy,jdbcType=VARCHAR}");
        }

        if (record.getRemoteAddr() != null) {
            SET("remote_addr = #{record.remoteAddr,jdbcType=VARCHAR}");
        }

        if (record.getUserAgent() != null) {
            SET("user_agent = #{record.userAgent,jdbcType=VARCHAR}");
        }

        if (record.getRequestUri() != null) {
            SET("request_uri = #{record.requestUri,jdbcType=VARCHAR}");
        }

        if (record.getMethod() != null) {
            SET("method = #{record.method,jdbcType=VARCHAR}");
        }

        if (record.getParams() != null) {
            SET("params = #{record.params,jdbcType=LONGVARCHAR}");
        }

        if (record.getException() != null) {
            SET("exception = #{record.exception,jdbcType=LONGVARCHAR}");
        }

        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("sys_log");

        SET("id = #{record.id,jdbcType=BIGINT}");
        SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
        SET("type = #{record.type,jdbcType=BIT}");
        SET("title = #{record.title,jdbcType=VARCHAR}");
        SET("create_by = #{record.createBy,jdbcType=VARCHAR}");
        SET("remote_addr = #{record.remoteAddr,jdbcType=VARCHAR}");
        SET("user_agent = #{record.userAgent,jdbcType=VARCHAR}");
        SET("request_uri = #{record.requestUri,jdbcType=VARCHAR}");
        SET("method = #{record.method,jdbcType=VARCHAR}");
        SET("params = #{record.params,jdbcType=LONGVARCHAR}");
        SET("exception = #{record.exception,jdbcType=LONGVARCHAR}");

        SysLogExample example = (SysLogExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("sys_log");

        SET("id = #{record.id,jdbcType=BIGINT}");
        SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
        SET("type = #{record.type,jdbcType=BIT}");
        SET("title = #{record.title,jdbcType=VARCHAR}");
        SET("create_by = #{record.createBy,jdbcType=VARCHAR}");
        SET("remote_addr = #{record.remoteAddr,jdbcType=VARCHAR}");
        SET("user_agent = #{record.userAgent,jdbcType=VARCHAR}");
        SET("request_uri = #{record.requestUri,jdbcType=VARCHAR}");
        SET("method = #{record.method,jdbcType=VARCHAR}");

        SysLogExample example = (SysLogExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(SysLogWithBLOBs record) {
        BEGIN();
        UPDATE("sys_log");

        if (record.getCreateDate() != null) {
            SET("create_date = #{createDate,jdbcType=TIMESTAMP}");
        }

        if (record.getType() != null) {
            SET("type = #{type,jdbcType=BIT}");
        }

        if (record.getTitle() != null) {
            SET("title = #{title,jdbcType=VARCHAR}");
        }

        if (record.getCreateBy() != null) {
            SET("create_by = #{createBy,jdbcType=VARCHAR}");
        }

        if (record.getRemoteAddr() != null) {
            SET("remote_addr = #{remoteAddr,jdbcType=VARCHAR}");
        }

        if (record.getUserAgent() != null) {
            SET("user_agent = #{userAgent,jdbcType=VARCHAR}");
        }

        if (record.getRequestUri() != null) {
            SET("request_uri = #{requestUri,jdbcType=VARCHAR}");
        }

        if (record.getMethod() != null) {
            SET("method = #{method,jdbcType=VARCHAR}");
        }

        if (record.getParams() != null) {
            SET("params = #{params,jdbcType=LONGVARCHAR}");
        }

        if (record.getException() != null) {
            SET("exception = #{exception,jdbcType=LONGVARCHAR}");
        }

        WHERE("id = #{id,jdbcType=BIGINT}");

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    protected void applyWhere(SysLogExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}
